In [1]:
import bmll2 as b2
b2.get_file('modules/auxiliary_functions_polars.py')
import auxiliary_functions_polars as af_pl

from bmll2 import reference, Security, NormalisedSecurity, SparkHelper, get_market_data, get_market_data_range, VenueMarketError, get_market_tables, save_spark_dataframe, load_spark_dataframe
import random
import math
import pandas as pd
import polars as pl
import numpy as np
from pandas import StringDtype
import gc
from typing import Literal

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.ticker import LogFormatterSciNotation
from statsmodels.tsa.stattools import acf
import statsmodels.api as sm
from scipy.optimize import curve_fit
from scipy.stats import t

In [26]:
b2.get_file('top_250.csv')
top_250 = pd.read_csv('top_250.csv')

top_250_tickers = top_250['Ticker'].tolist()

In [27]:
def load_stock(parquet):
    try:
        df = pl.read_parquet(parquet)
        return df.sort(['DateTime', 'ExchangeSequenceNo'])
    except FileNotFoundError:
        return None

In [28]:
def concave_profile_pl(stock_data, group = 'day', N = 4, participation_method = 'homogenous', alpha = 2):
    
    stock_data = stock_data.sort(['DateTime', 'ExchangeSequenceNo'], descending = False)

    if group == 'day':
        stock_data = stock_data.with_columns(pl.col('Date').alias('group key'))

    elif group == 'month':
        stock_data = stock_data.with_columns(pl.col('Date').dt.truncate('1mo').alias('group key'))
    
    elif group == 'year':
        stock_data = stock_data.with_columns(pl.col('Date').dt.truncate('1y').alias('group key'))

    impact_profile = []
    
    for trades in stock_data.partition_by('group key'):
        
        if trades.is_empty():
            continue

        trades = trades.sort(['DateTime', 'ExchangeSequenceNo'])
        f      = af_pl.trader_participation(N = N, method = participation_method, alpha = alpha, f_min = 1,
                                            f_max = trades.shape[0], seed = 1)
        c      = af_pl.cumulative_probs(f)
        output = af_pl.orders(N = N, trades = trades, cumulative_probs = c)
        
        assignments = []
        for trader_id, rows in enumerate(output):
            for r in rows:
                assignments.append((r, trader_id))

        assignments_df = pl.DataFrame(assignments, schema = ['row idx', 'trader id'], orient = 'row')

        trades = trades.with_row_index('row idx')
        trades = trades.join(assignments_df, on = 'row idx', how = 'inner')

        trades = trades.with_columns((pl.col('Trade Sign') != pl.col('Trade Sign').shift(1)).cast(pl.Int32)
            .cum_sum().over(['Date', 'trader id']).alias('metaorder id'))
            
        grouping_cols = ['Date', 'trader id', 'metaorder id']
        features = trades.with_columns([
            
            pl.col('Ticker'),
            pl.col('MIC'),

            pl.col('Daily Volume').first().over(grouping_cols),
            pl.col('Intraday Volatility').first().over(grouping_cols),
            pl.col('20 AD volume').first().over(grouping_cols),
            pl.col('20 AD volatility').first().over(grouping_cols),

            pl.col('Trade Sign').alias('trade sign'),

            pl.col('Volume').alias('volume'),
            pl.col('Volume').sum().over(grouping_cols).alias('volume traded'),
            (pl.col('Volume').cum_sum().over(grouping_cols) / pl.col('Volume').sum().over(grouping_cols)).alias('phi'),
            pl.len().over(grouping_cols).alias('number child orders'),
            
            pl.col('Mid-price before'),
            pl.col('Mid-price after'),
            #pl.col('Mid-price after (delayed)'),
            
            #pl.col('Mid-price before (1ms)'),
            #pl.col('Mid-price after (1ms)'),
            #pl.col('Mid-price after (1ms)(delayed)')

            (pl.col('Trade Sign').first().over(grouping_cols) * (pl.col('Mid-price after').last().log().over(grouping_cols) - pl.col('Mid-price before').first().log().over(grouping_cols))).alias('metaorder impact'),
            #(pl.col('Trade Sign').first().over(grouping_cols) * (pl.col('Mid-price after (1ms)').last().log().over(grouping_cols) - pl.col('Mid-price before (1ms)').first().log().over(grouping_cols))).alias('metaorder impact (1ms)')
        ])
        
        features = features.filter(pl.col('number child orders') > 4)
        
        features = features.with_columns([
            (pl.col('trade sign') * (pl.col('Mid-price after').log() - pl.col('Mid-price before').first().log().over(grouping_cols)) / (pl.col('20 AD volatility') * (pl.col('volume traded') / pl.col('20 AD volume')).sqrt())).alias('scaled impact'),
            #(pl.col('trade sign') * (pl.col('Mid-price after (1ms)').log() - pl.col('Mid-price before (1ms)').first().log().over(grouping_cols)) / (pl.col('20 AD volatility'))).alias('scaled impact (1ms)'),
    
        ])        
        features = features.select('MIC', 'Ticker', 'Date', 'DateTime', '20 AD volume', '20 AD volatility', 'trade sign',
                                   'trader id', 'metaorder id', 'number child orders', 'volume', 'volume traded',
                                   'phi', 'scaled impact', 'metaorder impact')
        
        impact_profile.append(features)

    if  impact_profile:
        return pl.concat(impact_profile, how = 'vertical', rechunk = True)
    else:
        return pl.DataFrame()

In [54]:
N                   = 20
trader_distribution = 'power'
alpha               = 2
group               = 'day'
identifier          = f'{trader_distribution}_{N}_{group}_pl'
exchange            = 'XJSE'

In [55]:
# only run this once!! Creates a folder to store all the data in
b2.create_folder('data', ensure_exists = True)
b2.create_folder('data/concave_profile', ensure_exists = True)
b2.create_folder(f'data/concave_profile/{exchange}', ensure_exists = True) 
b2.create_folder(f'data/concave_profile/{exchange}/{identifier}', ensure_exists = True)

In [58]:
ticker         = 'GRT'
b2.get_file(f'data/trades/top_250/{ticker}_{exchange}.parquet')
stock_data     = load_stock(f'{ticker}_{exchange}.parquet')
stock_data.head()

shape: (5, 19)
┌──────┬────────┬───────────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ MIC  ┆ Ticker ┆ ListingId ┆ Date       ┆ … ┆ Intraday    ┆ Daily       ┆ 20 AD      ┆ 20 AD      │
│ ---  ┆ ---    ┆ ---       ┆ ---        ┆   ┆ Volatility  ┆ Volume      ┆ volume     ┆ volatility │
│ str  ┆ str    ┆ i64       ┆ date       ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│      ┆        ┆           ┆            ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞══════╪════════╪═══════════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ XJSE ┆ GRT    ┆ 418405583 ┆ 2023-01-03 ┆ … ┆ 0.0293      ┆ 6.495675e6  ┆ 6.495675e6 ┆ 0.0293     │
│ XJSE ┆ GRT    ┆ 418405583 ┆ 2023-01-03 ┆ … ┆ 0.0293      ┆ 6.495675e6  ┆ 6.495675e6 ┆ 0.0293     │
│ XJSE ┆ GRT    ┆ 418405583 ┆ 2023-01-03 ┆ … ┆ 0.0293      ┆ 6.495675e6  ┆ 6.495675e6 ┆ 0.0293     │
│ XJSE ┆ GRT    ┆ 418405583 ┆ 2023-01-03 ┆ … ┆ 0.0293      ┆ 6.495675e6  ┆ 6.495675e6 ┆ 0.0293     │
│ XJSE ┆ GRT    ┆ 418405583 ┆ 2023-01-03 ┆ … ┆ 0.0293      ┆ 6.495675e6  ┆ 6.495675e6 ┆ 0.0293     │
└──────┴────────┴───────────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [59]:
%%time
concave_profile_data = concave_profile_pl(stock_data = stock_data, group = group, N = N,
                                          participation_method = trader_distribution,
                                          alpha = alpha)

concave_profile_data.write_parquet(f'{ticker}_{exchange}_concave_profile_data_{identifier}.parquet')
b2.put_file(f'{ticker}_{exchange}_concave_profile_data_{identifier}.parquet', f'data/concave_profile/{exchange}/{identifier}')

CPU times: user 32.5 s, sys: 5.23 s, total: 37.7 s
Wall time: 13.6 s

In [60]:
concave_profile_data.head()

shape: (5, 15)
┌──────┬────────┬────────────┬─────────────────┬───┬────────┬──────────┬───────────┬───────────┐
│ MIC  ┆ Ticker ┆ Date       ┆ DateTime        ┆ … ┆ volume ┆ phi      ┆ scaled    ┆ metaorder │
│ ---  ┆ ---    ┆ ---        ┆ ---             ┆   ┆ traded ┆ ---      ┆ impact    ┆ impact    │
│ str  ┆ str    ┆ date       ┆ datetime[μs]    ┆   ┆ ---    ┆ f64      ┆ ---       ┆ ---       │
│      ┆        ┆            ┆                 ┆   ┆ f64    ┆          ┆ f64       ┆ f64       │
╞══════╪════════╪════════════╪═════════════════╪═══╪════════╪══════════╪═══════════╪═══════════╡
│ XJSE ┆ GRT    ┆ 2023-01-03 ┆ 2023-01-03      ┆ … ┆ 4051.0 ┆ 0.108121 ┆ -0.0      ┆ -0.002406 │
│      ┆        ┆            ┆ 10:24:37.118383 ┆   ┆        ┆          ┆           ┆           │
│ XJSE ┆ GRT    ┆ 2023-01-03 ┆ 2023-01-03      ┆ … ┆ 4051.0 ┆ 0.117749 ┆ 0.470369  ┆ -0.002406 │
│      ┆        ┆            ┆ 10:24:42.197438 ┆   ┆        ┆          ┆           ┆           │
│ XJSE ┆ GRT    ┆ 2023-01-03 ┆ 2023-01-03      ┆ … ┆ 4051.0 ┆ 0.468526 ┆ 1.882449  ┆ -0.002406 │
│      ┆        ┆            ┆ 10:30:54.520616 ┆   ┆        ┆          ┆           ┆           │
│ XJSE ┆ GRT    ┆ 2023-01-03 ┆ 2023-01-03      ┆ … ┆ 4051.0 ┆ 0.60232  ┆ -0.470207 ┆ -0.002406 │
│      ┆        ┆            ┆ 10:30:59.265319 ┆   ┆        ┆          ┆           ┆           │
│ XJSE ┆ GRT    ┆ 2023-01-03 ┆ 2023-01-03      ┆ … ┆ 4051.0 ┆ 1.0      ┆ -3.28806  ┆ -0.002406 │
│      ┆        ┆            ┆ 10:37:38.403540 ┆   ┆        ┆          ┆           ┆           │
└──────┴────────┴────────────┴─────────────────┴───┴────────┴──────────┴───────────┴───────────┘

In [34]:
check = (
    concave_profile_data
    .with_columns(
        (
            pl.col("DateTime")
            .diff()
            .over(["trader id", "metaorder id"])
            <= pl.duration(microseconds=0)
        ).alias("not_strictly_increasing")
    )
)

violations = check.filter(pl.col("not_strictly_increasing") == True)

In [24]:
violations.height

0

In [25]:
violations

shape: (0, 16)
┌─────┬────────┬──────┬──────────────┬───┬─────┬───────────────┬───────────┬───────────────────────┐
│ MIC ┆ Ticker ┆ Date ┆ DateTime     ┆ … ┆ phi ┆ scaled impact ┆ metaorder ┆ not_strictly_increasi │
│ --- ┆ ---    ┆ ---  ┆ ---          ┆   ┆ --- ┆ ---           ┆ impact    ┆ ng                    │
│ str ┆ str    ┆ date ┆ datetime[μs] ┆   ┆ f64 ┆ f64           ┆ ---       ┆ ---                   │
│     ┆        ┆      ┆              ┆   ┆     ┆               ┆ f64       ┆ bool                  │
╞═════╪════════╪══════╪══════════════╪═══╪═════╪═══════════════╪═══════════╪═══════════════════════╡
└─────┴────────┴──────┴──────────────┴───┴─────┴───────────────┴───────────┴───────────────────────┘

In [20]:
concave_profile_data.height

1417191