In [1]:
pip install pandas openpyxl

Requirement already satisfied: pandas in /home/bmll/.conda/envs/py311-stable/lib/python3.11/site-packages (2.0.3)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/bmll/.conda/envs/py311-stable/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/bmll/.conda/envs/py311-stable/lib/python3.11/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /home/bmll/.conda/envs/py311-stable/lib/python3.11/site-packages (from pandas) (2025.1)
Requirement already satisfied: numpy>=1.21.0 in /home/bmll/.conda/envs/py311-stable/lib/python3.11/site-packages (from pandas) (1.26.0)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in /home/bmll/.conda/envs/py311-stable/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import polars as pl
import numpy as np
import datetime as dt
import plotly.express as px

import bmll2 as b2
from bmll2 import reference, Security, NormalisedSecurity, SparkHelper, get_market_data, get_market_data_range, VenueMarketError, save_spark_dataframe, load_spark_dataframe, get_market_tables, get_df_engines

pd.options.display.max_columns = None

In [3]:
def get_data(exchange, ticker, starting_date, ending_date):

    try:
        trades_plus = get_market_data_range([exchange], start_date = starting_date, end_date = ending_date,
                                   table_name = 'trades-plus', df_engine = 'polars', ticker = ticker,
                                   columns = ['Classification', 'MIC', 'Ticker', 'ListingId', 'TradeDate',
                                              'LocalTradeTimestamp', 'ExchangeSequenceNo', 'AggressorSide',
                                              'Price', 'Size', 'BestBidPriceAtPrimary', 'BestAskPriceAtPrimary',
                                              'PreTradeMid1msAtPrimary', 'PostTradeMid1msAtPrimary', 'PostTradeMidAtPrimary'])
    except VenueMarketError:
        return None
    
    trades_plus = trades_plus.filter((pl.col('LocalTradeTimestamp').dt.time() >= pl.time(9, 10)) &
                   (pl.col('LocalTradeTimestamp').dt.time() <= pl.time(16, 50)))
    trades_plus = trades_plus.filter(pl.col('Classification') == 'LIT_CONTINUOUS')
    
    if trades_plus is None or trades_plus.is_empty():
        return None
    
    columns     = ['MIC', 'Ticker', 'ListingId', 'TradeDate', 'LocalTradeTimestamp', 'ExchangeSequenceNo',
                   'AggressorSide', 'Price', 'Size', 'BestBidPriceAtPrimary', 'BestAskPriceAtPrimary',
                   'PreTradeMid1msAtPrimary', 'PostTradeMidAtPrimary', 'PostTradeMid1msAtPrimary']
    trades_plus = trades_plus.select(columns)
    
    trades_plus = trades_plus.with_columns((0.5 * (pl.col('BestBidPriceAtPrimary') + pl.col('BestAskPriceAtPrimary'))).alias('Mid-price before'))
    
    trades_plus = trades_plus.with_columns(pl.col('AggressorSide').replace({1: 1, 2: -1, 0: 0}).alias('Trade Sign'))
    trades_plus = trades_plus.filter(pl.col('Trade Sign').is_in([-1, 1]))
    trades_plus = trades_plus.rename({'PreTradeMid1msAtPrimary' : 'Mid-price before (1ms)',
                                      'PostTradeMid1msAtPrimary' : 'Mid-price after (1ms)',
                                      'PostTradeMidAtPrimary' : 'Mid-price after',
                                      'Size' : 'Volume', 'LocalTradeTimestamp' : 'DateTime', 'TradeDate' : 'Date'})
    trades_plus = trades_plus.with_columns(pl.col('Mid-price before').shift(-1).alias('Mid-price after (delayed)'))
    trades_plus = trades_plus.with_columns(pl.col('Mid-price before (1ms)').shift(-1).alias('Mid-price after (1ms)(delayed)'))
    
    columns     = ['MIC', 'Ticker', 'ListingId', 'Date', 'DateTime', 'ExchangeSequenceNo',
                   'Trade Sign', 'Price', 'Volume', 'Mid-price before (1ms)', 'Mid-price after (1ms)', 'Mid-price after (1ms)(delayed)',
                   'Mid-price before', 'Mid-price after', 'Mid-price after (delayed)']
    trades_plus = trades_plus.select(columns)

                                           
    l1 = get_market_data_range('XJSE', start_date = starting_date, end_date = ending_date, ticker = 'GRT',
                                   table_name = 'l1', df_engine = 'polars')
    
    l1 = l1.filter((pl.col('LocalTimestamp').dt.time() >= pl.time(9, 10)) &
                   (pl.col('LocalTimestamp').dt.time() <= pl.time(16, 50)))
    l1 = l1.filter(pl.col('MarketState') == 'CONTINUOUS_TRADING')
    l1 = l1.with_columns(((pl.col('AskPrice1') + pl.col('BidPrice1')) / 2).alias('Mid-price'))
    l1 = l1.rename({'TradeDate' : 'Date'})
    l1 = l1.sort(['Date', 'ExchangeSequenceNo'])
    daily_volatility = l1.group_by('Date').agg(((pl.col('Mid-price').max() - pl.col('Mid-price').min()) / pl.col('Mid-price').drop_nulls().first()).alias('Intraday Volatility'))
    daily_volume = trades_plus.group_by('Date').agg(pl.col('Volume').sum().alias('Daily Volume'))

    trades = trades_plus.join(daily_volatility, on = 'Date', how = 'left').join(daily_volume, on = 'Date', how = 'left')

    data  = trades.clone()
    daily = data.group_by(['Date']).agg([pl.col('Daily Volume').first().alias('Daily Volume'),
                                         pl.col('Intraday Volatility').first().alias('Intraday Volatility')]).sort(['Date'])
    
    n     = 20
    daily = daily.with_columns([pl.col('Daily Volume').rolling_mean(n, min_samples = 1).alias(f'{n} AD volume'),
                                pl.col('Intraday Volatility').rolling_mean(n, min_samples = 1).alias(f'{n} AD volatility')])
    trades = trades.join(daily.select(['Date', f'{n} AD volume', f'{n} AD volatility']), on = ['Date'], how = 'left')
    
    trades = trades.sort(['DateTime', 'ExchangeSequenceNo'])
    return trades

In [4]:
b2.get_file('companies_list.csv')

JSE_listed_securities = pl.read_csv('companies_list.csv')
JSE_listed_securities = JSE_listed_securities.with_columns([pl.col('Code').str.strip_chars().str.replace('JSE:', '').alias('Code'),
                                                            pl.col('Market Cap').str.strip_chars().cast(pl.Float64).alias('Market Cap')])
JSE_listed_securities = JSE_listed_securities.rename({'Code': 'Ticker'})
JSE_listed_securities = JSE_listed_securities.sort('Market Cap', descending = True)

top_50 = JSE_listed_securities[0:50, :]
top_100 = JSE_listed_securities[0:100, :]
top_250 = JSE_listed_securities[0:250, :]

top_50.write_csv('top_50.csv')
top_100.write_csv('top_100.csv')
top_250.write_csv('top_250.csv')

b2.put_file('top_50.csv')
b2.put_file('top_100.csv')
b2.put_file('top_250.csv')

In [5]:
%%time
trade_data = get_data('XJSE', 'AGL', '2023-01-03', '2023-01-04')

CPU times: user 603 ms, sys: 311 ms, total: 914 ms
Wall time: 3.63 s

In [7]:
trade_data.head()

shape: (5, 19)
┌──────┬────────┬───────────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ MIC  ┆ Ticker ┆ ListingId ┆ Date       ┆ … ┆ Intraday    ┆ Daily       ┆ 20 AD      ┆ 20 AD      │
│ ---  ┆ ---    ┆ ---       ┆ ---        ┆   ┆ Volatility  ┆ Volume      ┆ volume     ┆ volatility │
│ str  ┆ str    ┆ i64       ┆ date       ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│      ┆        ┆           ┆            ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞══════╪════════╪═══════════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ XJSE ┆ AGL    ┆ 418405540 ┆ 2023-01-03 ┆ … ┆ 0.0293      ┆ 449528.0    ┆ 449528.0   ┆ 0.0293     │
│ XJSE ┆ AGL    ┆ 418405540 ┆ 2023-01-03 ┆ … ┆ 0.0293      ┆ 449528.0    ┆ 449528.0   ┆ 0.0293     │
│ XJSE ┆ AGL    ┆ 418405540 ┆ 2023-01-03 ┆ … ┆ 0.0293      ┆ 449528.0    ┆ 449528.0   ┆ 0.0293     │
│ XJSE ┆ AGL    ┆ 418405540 ┆ 2023-01-03 ┆ … ┆ 0.0293      ┆ 449528.0    ┆ 449528.0   ┆ 0.0293     │
│ XJSE ┆ AGL    ┆ 418405540 ┆ 2023-01-03 ┆ … ┆ 0.0293      ┆ 449528.0    ┆ 449528.0   ┆ 0.0293     │
└──────┴────────┴───────────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [8]:
trade_data.tail()

shape: (5, 19)
┌──────┬────────┬───────────┬────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ MIC  ┆ Ticker ┆ ListingId ┆ Date       ┆ … ┆ Intraday    ┆ Daily       ┆ 20 AD      ┆ 20 AD      │
│ ---  ┆ ---    ┆ ---       ┆ ---        ┆   ┆ Volatility  ┆ Volume      ┆ volume     ┆ volatility │
│ str  ┆ str    ┆ i64       ┆ date       ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│      ┆        ┆           ┆            ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞══════╪════════╪═══════════╪════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ XJSE ┆ AGL    ┆ 418405540 ┆ 2023-01-04 ┆ … ┆ 0.013432    ┆ 629586.0    ┆ 539557.0   ┆ 0.021366   │
│ XJSE ┆ AGL    ┆ 418405540 ┆ 2023-01-04 ┆ … ┆ 0.013432    ┆ 629586.0    ┆ 539557.0   ┆ 0.021366   │
│ XJSE ┆ AGL    ┆ 418405540 ┆ 2023-01-04 ┆ … ┆ 0.013432    ┆ 629586.0    ┆ 539557.0   ┆ 0.021366   │
│ XJSE ┆ AGL    ┆ 418405540 ┆ 2023-01-04 ┆ … ┆ 0.013432    ┆ 629586.0    ┆ 539557.0   ┆ 0.021366   │
│ XJSE ┆ AGL    ┆ 418405540 ┆ 2023-01-04 ┆ … ┆ 0.013432    ┆ 629586.0    ┆ 539557.0   ┆ 0.021366   │
└──────┴────────┴───────────┴────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [9]:
exchange = 'XJSE'
ticker = 'GRT'
starting_date = '2023-01-03'
ending_date = '2023-01-31'

In [6]:
start_dates = pl.date_range(start = dt.date(2023, 1, 1), end = dt.date(2025, 12, 1),
                            interval = '12mo', closed = 'left', eager = True)
end_dates   = start_dates.dt.offset_by('12mo').dt.offset_by('-1d')

In [7]:
b2.create_folder('data', ensure_exists = True)
b2.create_folder('data/trades', ensure_exists = True)
b2.create_folder('data/trades/top_250', ensure_exists = True)

In [8]:
top_250_tickers = top_250['Ticker'].to_list()

In [13]:
%%time
# A2XX or XJSE
exchange = 'XJSE'
counter = 0
for ticker in top_250_tickers:
    counter += 1
    stock = []
    for i in range(len(start_dates)):
        data = get_data(exchange, ticker, start_dates[i], end_dates[i])
        if data is not None and not data.is_empty():
            stock.append(data)

    if len(stock) == 0:
        continue

    stock_data = pl.concat(stock, how = 'vertical')
    stock_data = stock_data.sort(['DateTime', 'ExchangeSequenceNo'])
    stock_data.write_parquet(f'{ticker}_{exchange}.parquet')
    b2.put_file(f'{ticker}_{exchange}.parquet', 'data/trades/top_250')
    print(f'{counter}: {ticker}')


# takes about 1.5 hours to run

1: MDI
2: JBL
3: OAO
4: CLH
5: SDL
6: ZZD
7: YYLBEE
8: CTA
9: QFH
10: GML
11: ZED
12: SCD
13: NVS
14: ART
16: BWN
17: OAS
18: APF
19: MMP
20: EPS
21: EMN
22: MCZ
23: ACL
24: BRN
25: UPL
27: TPC
28: BCF
29: TEX
30: DNB
31: EPE
32: TCP
33: SSK
34: YRK
35: GPL
36: SNV
37: MST
38: MTA
39: WEZ
40: PBG
41: ENX
42: HLM
43: ACT
44: RMH
45: ADR
46: FGL
47: NWL
49: AEG
50: CGR
51: SEP
52: NRL
53: SOLBE1
54: ISA
55: VUN
56: 4SI
57: TTO
59: AME
60: PMV
61: CKS
62: RTN
63: PPR
64: HUG
65: DLT
66: TMT
68: ISB
69: BRT
70: SOH
71: CAC
73: EMH
74: KBO
75: AON
76: TRL
77: NCS
78: TLM
79: RHB
81: LAB
82: RNG
83: SEB
84: BIK
85: GLI
86: RTO
87: VIS
88: AOO
89: EUZ
90: EEL
91: ADW
CPU times: user 1h 18min 21s, sys: 35min 23s, total: 1h 53min 45s
Wall time: 1h 13min 13s