In [1]:
import bmll2 as b2
b2.get_file('modules/auxiliary_functions_polars.py')
import auxiliary_functions_polars as af_pl

from bmll2 import reference, Security, NormalisedSecurity, SparkHelper, get_market_data, get_market_data_range, VenueMarketError, get_market_tables, save_spark_dataframe, load_spark_dataframe
import random
import math
import pandas as pd
import polars as pl
import numpy as np
from pandas import StringDtype
import gc
from typing import Literal

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.ticker import LogFormatterSciNotation
from statsmodels.tsa.stattools import acf
import statsmodels.api as sm
from scipy.optimize import curve_fit
from scipy.stats import t

In [2]:
b2.get_file('top_250.csv')
top_250 = pd.read_csv('top_250.csv')

top_250_tickers = top_250['Ticker'].tolist()

In [3]:
def load_stock(parquet):
    try:
        df = pl.read_parquet(parquet)
        return df.sort(['DateTime', 'ExchangeSequenceNo'])
    except FileNotFoundError:
        return None

In [4]:
def process_stock_pl(stock_data, group = 'day', N = 4, participation_method = 'homogenous', alpha = 2,
                     impact_method = 'simple'):
    
    #stock_data = stock_data.sort(['DateTime', 'ExchangeSequenceNo'], descending = False)

    if group == 'day':
        stock_data = stock_data.with_columns(pl.col('Date').alias('group key'))

    elif group == 'month':
        stock_data = stock_data.with_columns(pl.col('Date').dt.truncate('1mo').alias('group key'))
    
    elif group == 'year':
        stock_data = stock_data.with_columns(pl.col('Date').dt.truncate('1y').alias('group key'))

    features_list_pl = []
    
    for trades in stock_data.partition_by('group key'):

        if trades.is_empty():
            continue

        trades = trades.sort(['DateTime', 'ExchangeSequenceNo'])

        f      = af_pl.trader_participation(N = N, method = participation_method, alpha = alpha, f_min = 1,
                                            f_max = trades.shape[0], seed = 1)
        c      = af_pl.cumulative_probs(f)
        output = af_pl.orders(N = N, trades = trades, cumulative_probs = c)
        
        assignments = []
        for trader_id, rows in enumerate(output):
            for r in rows:
                assignments.append((r, trader_id))

        assignments_df = pl.DataFrame(assignments, schema = ['row idx', 'trader id'], orient = 'row')

        trades = trades.sort(['Date', 'DateTime', 'ExchangeSequenceNo'])
        trades = trades.with_row_index('row idx')
        trades = trades.join(assignments_df, on = 'row idx', how = 'inner')

        trades = trades.with_columns((pl.col('Trade Sign') != pl.col('Trade Sign').shift(1)).cast(pl.Int32)
            .cum_sum().over(['Date', 'trader id']).alias('metaorder id'))

        features = trades.group_by(['Date', 'trader id', 'metaorder id']
        ).agg([

            pl.col('Ticker').first(),
            pl.col('MIC').first(),
            pl.col('DateTime').first().alias('Start time'),
            pl.col('DateTime').last().alias('End time'),

            pl.col('Daily Volume').first(),
            pl.col('Intraday Volatility').first(),
            pl.col('20 AD volume').first(),
            pl.col('20 AD volatility').first(),

            pl.col('Trade Sign').first().alias('trade sign'),
            
            pl.col('Volume').sum().alias('volume traded'),
            pl.len().alias('number child orders'),
            
            pl.col('Mid-price before').first(),
            pl.col('Mid-price after').last(),
        ])

        features = features.filter(pl.col('number child orders') > 4)

        features = features.with_columns([
            ((pl.col('Mid-price after').log() - pl.col('Mid-price before').log())
             * pl.col('trade sign')).alias('impact'),

            (((pl.col('End time') - pl.col('Start time')).dt.total_microseconds()).alias('duration (ms)'))
        ])
        
        features_list_pl.append(features)

    if features_list_pl:
        return pl.concat(features_list_pl, how = 'vertical', rechunk = True)
    else:
        return pl.DataFrame()

In [18]:
N                   = 20
trader_distribution = 'power'
alpha               = 2
group               = 'day'
identifier          = f'{trader_distribution}_{N}_{group}_pl'
exchange            = 'XJSE'

In [19]:
# only run this once!! Creates a folder to store all the data in
b2.create_folder('data', ensure_exists = True)
b2.create_folder('data/impact_decay', ensure_exists = True)
b2.create_folder(f'data/impact_decay/{exchange}', ensure_exists = True)
b2.create_folder(f'data/impact_decay/{exchange}/{identifier}', ensure_exists = True)

In [20]:
ticker     = 'AGL'
b2.get_file(f'data/trades/top_250/{ticker}_{exchange}.parquet')
stock_data = load_stock(f'{ticker}_{exchange}.parquet')

In [21]:
%%time
metaorder_data = process_stock_pl(stock_data, group = group, N = N, participation_method = trader_distribution, alpha = alpha,
                                  impact_method = 'simple')

metaorder_data.write_parquet(f'{ticker}_{exchange}_metaorder_data_{identifier}.parquet')
b2.put_file(f'{ticker}_{exchange}_metaorder_data_{identifier}.parquet', f'data/impact_decay/{exchange}/{identifier}')

CPU times: user 35.7 s, sys: 5.01 s, total: 40.7 s
Wall time: 25.2 s

In [22]:
b2.get_file(f'data/impact_decay/{exchange}/{identifier}/{ticker}_{exchange}_metaorder_data_{identifier}.parquet')
metaorder_data = pl.read_parquet(f'{ticker}_{exchange}_metaorder_data_{identifier}.parquet')

In [23]:
%%time
stock_mid_prices = get_market_data_range('XJSE', start_date = '2023-01-03', end_date = '2025-12-31',
                                       table_name = 'l1', ticker = ticker, df_engine = 'polars',
                                      columns = ['Ticker', 'TradeDate', 'LocalTimestamp', 'BidPrice1', 'BidQuantity1', 'AskPrice1', 'AskQuantity1',
                                                 'ExchangeSequenceNo', 'MarketState'])
stock_mid_prices = stock_mid_prices.filter(pl.col('MarketState') == 'CONTINUOUS_TRADING')
stock_mid_prices = stock_mid_prices.sort(['LocalTimestamp', 'ExchangeSequenceNo'])
stock_mid_prices = stock_mid_prices.with_columns(((pl.col('BidPrice1') + pl.col('AskPrice1')) / 2).alias('Mid-price'))
stock_mid_prices = stock_mid_prices.sort('LocalTimestamp')

CPU times: user 53.1 s, sys: 20.2 s, total: 1min 13s
Wall time: 48.5 s

In [24]:
metaorder_data.head()

shape: (5, 18)
┌────────────┬───────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Date       ┆ trader id ┆ metaorder  ┆ Ticker ┆ … ┆ Mid-price ┆ Mid-price ┆ impact    ┆ duration  │
│ ---        ┆ ---       ┆ id         ┆ ---    ┆   ┆ before    ┆ after     ┆ ---       ┆ (ms)      │
│ date       ┆ i64       ┆ ---        ┆ str    ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ---       │
│            ┆           ┆ i32        ┆        ┆   ┆ f64       ┆ f64       ┆           ┆ i64       │
╞════════════╪═══════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2023-01-03 ┆ 2         ┆ 27         ┆ AGL    ┆ … ┆ 66184.5   ┆ 66665.0   ┆ -0.007234 ┆ 263962734 │
│            ┆           ┆            ┆        ┆   ┆           ┆           ┆           ┆ 7         │
│ 2023-01-03 ┆ 13        ┆ 13         ┆ AGL    ┆ … ┆ 66501.5   ┆ 66429.0   ┆ 0.001091  ┆ 348072893 │
│ 2023-01-03 ┆ 8         ┆ 20         ┆ AGL    ┆ … ┆ 66904.5   ┆ 66707.5   ┆ 0.002949  ┆ 442057679 │
│ 2023-01-03 ┆ 0         ┆ 70         ┆ AGL    ┆ … ┆ 66362.0   ┆ 66212.5   ┆ 0.002255  ┆ 959333774 │
│ 2023-01-03 ┆ 3         ┆ 8          ┆ AGL    ┆ … ┆ 66196.5   ┆ 66378.5   ┆ -0.002746 ┆ 179540929 │
└────────────┴───────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [25]:
%%time
z_max  = 2
z_grid = np.linspace(1, z_max, 100)

meta = metaorder_data.filter(pl.col('number child orders') > 4)
meta = meta.sort('Start time')

expanded = meta.with_row_index('meta id').join(pl.DataFrame({'z': z_grid}), how = 'cross')
expanded = expanded.with_columns((pl.col('Start time') + pl.duration(microseconds = (pl.col('z') * (pl.col('End time') - pl.col('Start time')).dt.total_microseconds()).cast(pl.Int64))).alias('query time'))
expanded = expanded.sort('query time')

merged = expanded.join_asof(stock_mid_prices, left_on = 'query time', right_on = 'LocalTimestamp', strategy = 'backward')
merged = merged.filter(pl.col('LocalTimestamp') >= pl.col('End time'))
merged = merged.with_columns([pl.col('Mid-price before').alias('P0'), pl.col('Mid-price').alias('Pz')])
merged = merged.with_columns((pl.col('trade sign') * (pl.col('Pz').log() - pl.col('P0').log())).alias('impact'))
merged = merged.with_columns((pl.col('impact') / (pl.col('20 AD volatility') * (pl.col('volume traded') / pl.col('20 AD volume')).sqrt())).alias('scaled impact'))

decay_df = merged.select(['Date', 'z', 'impact', 'scaled impact'])
decay_df.write_parquet(f'{ticker}_{exchange}_impact_decay_{identifier}.parquet')
b2.put_file(f'{ticker}_{exchange}_impact_decay_{identifier}.parquet', f'data/impact_decay/{exchange}/{identifier}')

CPU times: user 10.2 s, sys: 1.23 s, total: 11.4 s
Wall time: 4.82 s

In [26]:
decay_df[0:9, : ]

shape: (9, 4)
┌────────────┬──────────┬──────────┬───────────────┐
│ Date       ┆ z        ┆ impact   ┆ scaled impact │
│ ---        ┆ ---      ┆ ---      ┆ ---           │
│ date       ┆ f64      ┆ f64      ┆ f64           │
╞════════════╪══════════╪══════════╪═══════════════╡
│ 2023-01-03 ┆ 1.0      ┆ 0.002569 ┆ 2.215464      │
│ 2023-01-03 ┆ 1.010101 ┆ 0.003028 ┆ 2.611219      │
│ 2023-01-03 ┆ 1.020202 ┆ 0.003035 ┆ 2.617708      │
│ 2023-01-03 ┆ 1.030303 ┆ 0.003035 ┆ 2.617708      │
│ 2023-01-03 ┆ 1.040404 ┆ 0.003035 ┆ 2.617708      │
│ 2023-01-03 ┆ 1.050505 ┆ 0.002862 ┆ 2.468467      │
│ 2023-01-03 ┆ 1.060606 ┆ 0.002862 ┆ 2.468467      │
│ 2023-01-03 ┆ 1.070707 ┆ 0.002832 ┆ 2.442514      │
│ 2023-01-03 ┆ 1.080808 ┆ 0.002764 ┆ 2.384124      │
└────────────┴──────────┴──────────┴───────────────┘