In [3]:
import bmll2 as b2
b2.get_file('modules/auxiliary_functions_polars.py')
import auxiliary_functions_polars as af_pl

from bmll2 import reference, Security, NormalisedSecurity, SparkHelper, get_market_data, get_market_data_range, VenueMarketError, get_market_tables, save_spark_dataframe, load_spark_dataframe
import random
import math
import pandas as pd
import polars as pl
import numpy as np
from pandas import StringDtype
import gc
from typing import Literal

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.ticker import LogFormatterSciNotation
from statsmodels.tsa.stattools import acf
import statsmodels.api as sm
from scipy.optimize import curve_fit
from scipy.stats import t

In [4]:
%%time
files = b2.list_files(path = 'top_100(Volume)')

for f in files:
    b2.get_file(f'top_100(Volume)/{f}')
    
def load_stock(csv):
    df = pl.read_csv(csv, try_parse_dates = True) #['DateTime', 'Date']
    df = df.rename({'Ticker': 'RIC'})
    df = df.sort(['DateTime', 'ExchangeSequenceNo'], descending = False)
    return df

CPU times: user 58 s, sys: 1min 11s, total: 2min 9s
Wall time: 2min 4s

In [16]:
def impact_df_decay(metaorders_list, timing_method = 'immediate', impact_method = 'simple'): 
    
    num_metaorders = len(metaorders_list)

    rows = []
    for i in range(num_metaorders):
        metaorder = metaorders_list[i]
        metaorder = metaorder.with_columns([pl.col('Mid-price before').fill_null(float('nan')),
                                pl.col('Mid-price after(immediate)').fill_null(float('nan'))])    
        if metaorder.is_empty():
            continue

        intention  = metaorder[0, 'Trade Sign']
        ave_impact = af_pl.impact(metaorder, timing_method = timing_method, impact_method = impact_method)
        n          = metaorder.shape[0]
        volume     = metaorder['Volume'].sum()

        rows.append({
            'RIC'                : metaorder['RIC'][0],
            'Date'               : metaorder['Date'][0],
            'Start time'         : metaorder['DateTime'][0],
            'End time'           : metaorder['DateTime'][-1],
            'daily volume'       : metaorder['Daily Volume'][0],
            'intraday volatility': metaorder['Daily Volatility'][0],
            'number child orders': n,
            'volume traded'      : volume,
            'trade sign'         : intention,
            'impact'             : ave_impact,
            'Mid-price before'   : metaorder['Mid-price before'][0],
            'Mid-prife after'    : metaorder['Mid-price after(immediate)'][-1]})
        
    schema = {
        'RIC'                : pl.String,
        'Date'               : pl.Date,
        'Start time'         : pl.Datetime('us'),
        'End time'           : pl.Datetime('us'),
        'daily volume'       : pl.Float64,
        'intraday volatility': pl.Float64,
        'number child orders': pl.Int64,
        'volume traded'      : pl.Float64,
        'trade sign'         : pl.Int64,
        'impact'             : pl.Float64,
        'Mid-price before'   : pl.Float64,
        'Mid-price after'    : pl.Float64}

    features = pl.DataFrame(rows, schema = schema).sort('Start time', descending = False)
    return features

In [17]:
def process_stock_pl(stock_data, group = 'day', N = 4, participation_method = 'homogenous', alpha = 2,
                     timing_method = 'immediate', impact_method = 'simple'):
    
    stock_data = stock_data.sort(['DateTime', 'ExchangeSequenceNo'], descending = False)

    if group == 'day':
        stock_data = stock_data.with_columns(pl.col('Date').alias('group key'))

    elif group == 'month':
        stock_data = stock_data.with_columns(pl.col('Date').dt.truncate('1mo').alias('group key'))
    
    elif group == 'year':
        stock_data = stock_data.with_columns(pl.col('Date').dt.truncate('1y').alias('group key'))

    features_list_pl = []
    
    for day_D in stock_data.partition_by('group key'):

        date   = day_D['group key'][0]
        trades = day_D
        
        if trades.is_empty():
            continue

        f = af_pl.trader_participation(N = N, method = participation_method, alpha = alpha, f_min = 1, f_max = trades.shape[0], seed = 1)
        c = af_pl.cumulative_probs(f)
        output = af_pl.orders(N = N, trades = trades, cumulative_probs = c)

        for n in range(N):
            trader_n_trades = trades[output[n], :]

            if trader_n_trades.is_empty():
                continue
        
            trader_n_metaorders = af_pl.metaorders(trader_n_trades)
        
            if len(trader_n_metaorders) == 0:
                continue
        
            trader_n_features = impact_df_decay(trader_n_metaorders, timing_method = 'immediate', impact_method = 'simple')
        
            features_list_pl.append(trader_n_features)

    if features_list_pl:
        return pl.concat(features_list_pl, how = 'vertical', rechunk = True)
    else:
        return pl.DataFrame()

In [38]:
ticker     = 'GFI'
stock_data = load_stock(f'{ticker}.csv')

In [39]:
N                   = 20
trader_distribution = 'power'
alpha               = 2
group               = 'day'
identifier          = f'{trader_distribution}_{N}_{group}_pl'

In [40]:
# only run this once!! Creates a folder to store all the data in
b2.create_folder('data', ensure_exists = True)
b2.create_folder('data/impact_decay', ensure_exists = True)
b2.create_folder(f'data/impact_decay/{identifier}', ensure_exists = True)

In [42]:
%%time
metaorder_data = process_stock_pl(stock_data, group = group, N = N, participation_method = trader_distribution, alpha = alpha,
                                  timing_method = 'immediate', impact_method = 'simple')

CPU times: user 23min 10s, sys: 6min 53s, total: 30min 4s
Wall time: 6min 10s

In [43]:
data  = metaorder_data.clone()
daily = data.group_by(['RIC', 'Date']).agg([pl.col('daily volume').first().alias('daily volume'),
                                            pl.col('intraday volatility').first().alias('intraday volatility')]).sort(['RIC', 'Date'])

n     = 20
daily = daily.with_columns([pl.col('daily volume').rolling_mean(n, min_samples = 1).over('RIC').alias(f'{n} AD volume'),
                            pl.col('intraday volatility').rolling_mean(n, min_samples = 1).over('RIC').alias(f'{n} AD volatility')])
data = data.join(daily.select(['RIC', 'Date', f'{n} AD volume', f'{n} AD volatility']),on = ['RIC', 'Date'], how = 'left')

data = data.with_columns(((data['End time'] - data['Start time']).dt.total_microseconds() / 6e7).alias('durations (min)'))

data.write_parquet(f'{ticker}_metaorder_data_{identifier}.parquet')
b2.put_file(f'{ticker}_metaorder_data_{identifier}.parquet', f'data/impact_decay/{identifier}')

In [44]:
N                   = 20
trader_distribution = 'power'
alpha               = 2
group               = 'day'
identifier          = f'{trader_distribution}_{N}_{group}_pl'

In [45]:
# only run this once!! Creates a folder to store all the data in
b2.create_folder('data', ensure_exists = True)
b2.create_folder('data/impact_decay', ensure_exists = True)
b2.create_folder(f'data/impact_decay/{identifier}', ensure_exists = True)

In [46]:
b2.get_file(f'data/impact_decay/{identifier}/{ticker}_metaorder_data_{identifier}.parquet')
metaorder_data = pl.read_parquet(f'{ticker}_metaorder_data_{identifier}.parquet')

In [27]:
metaorder_data.head()

shape: (5, 15)
┌─────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ RIC ┆ Date       ┆ Start time ┆ End time   ┆ … ┆ Mid-price  ┆ 20 AD      ┆ 20 AD vol ┆ durations │
│ --- ┆ ---        ┆ ---        ┆ ---        ┆   ┆ after      ┆ volume     ┆ atility   ┆ (min)     │
│ str ┆ date       ┆ datetime[μ ┆ datetime[μ ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│     ┆            ┆ s]         ┆ s]         ┆   ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
╞═════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ GRT ┆ 2023-01-03 ┆ 2023-01-03 ┆ 2023-01-03 ┆ … ┆ null       ┆ 6.862853e6 ┆ 0.035155  ┆ 39.556659 │
│     ┆            ┆ 09:20:48.7 ┆ 10:00:22.1 ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆ 34415      ┆ 33972      ┆   ┆            ┆            ┆           ┆           │
│ GRT ┆ 2023-01-03 ┆ 2023-01-03 ┆ 2023-01-03 ┆ … ┆ null       ┆ 6.862853e6 ┆ 0.035155  ┆ 6.86934   │
│     ┆            ┆ 10:17:42.9 ┆ 10:24:35.1 ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆ 40561      ┆ 00951      ┆   ┆            ┆            ┆           ┆           │
│ GRT ┆ 2023-01-03 ┆ 2023-01-03 ┆ 2023-01-03 ┆ … ┆ null       ┆ 6.862853e6 ┆ 0.035155  ┆ 0.0462922 │
│     ┆            ┆ 10:35:31.5 ┆ 10:35:34.3 ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆ 32083      ┆ 09615      ┆   ┆            ┆            ┆           ┆           │
│ GRT ┆ 2023-01-03 ┆ 2023-01-03 ┆ 2023-01-03 ┆ … ┆ null       ┆ 6.862853e6 ┆ 0.035155  ┆ 3.796354  │
│     ┆            ┆ 10:35:50.4 ┆ 10:39:38.2 ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆ 36098      ┆ 17363      ┆   ┆            ┆            ┆           ┆           │
│ GRT ┆ 2023-01-03 ┆ 2023-01-03 ┆ 2023-01-03 ┆ … ┆ null       ┆ 6.862853e6 ┆ 0.035155  ┆ 0.095592  │
│     ┆            ┆ 10:39:39.6 ┆ 10:39:45.3 ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆ 60790      ┆ 96306      ┆   ┆            ┆            ┆           ┆           │
└─────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [47]:
%%time
stock_mid_prices = get_market_data_range('XJSE', start_date = '2023-01-03', end_date = '2025-12-31',
                                       table_name = 'l1', ticker = ticker, df_engine = 'polars',
                                      columns = ['Ticker', 'TradeDate', 'LocalTimestamp', 'BidPrice1', 'BidQuantity1', 'AskPrice1', 'AskQuantity1',
                                                 'ExchangeSequenceNo', 'MarketState'])
stock_mid_prices = stock_mid_prices.filter(pl.col('MarketState') == 'CONTINUOUS_TRADING')
stock_mid_prices = stock_mid_prices.sort('LocalTimestamp')
stock_mid_prices = stock_mid_prices.with_columns(((pl.col('BidPrice1') + pl.col('AskPrice1')) / 2).alias('Mid-price'))

CPU times: user 37.4 s, sys: 21 s, total: 58.4 s
Wall time: 32.9 s

In [52]:
stock_mid_prices.head()

shape: (5, 10)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Ticker ┆ TradeDate  ┆ LocalTimes ┆ BidPrice1 ┆ … ┆ AskQuanti ┆ ExchangeS ┆ MarketSta ┆ Mid-price │
│ ---    ┆ ---        ┆ tamp       ┆ ---       ┆   ┆ ty1       ┆ equenceNo ┆ te        ┆ ---       │
│ str    ┆ date       ┆ ---        ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│        ┆            ┆ datetime[μ ┆           ┆   ┆ i64       ┆ i64       ┆ str       ┆           │
│        ┆            ┆ s]         ┆           ┆   ┆           ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ GFI    ┆ 2023-01-03 ┆ 2023-01-03 ┆ 17800.0   ┆ … ┆ 308       ┆ 37359     ┆ CONTINUOU ┆ 17889.5   │
│        ┆            ┆ 09:00:17.3 ┆           ┆   ┆           ┆           ┆ S_TRADING ┆           │
│        ┆            ┆ 38527      ┆           ┆   ┆           ┆           ┆           ┆           │
│ GFI    ┆ 2023-01-03 ┆ 2023-01-03 ┆ 17800.0   ┆ … ┆ 308       ┆ 37475     ┆ CONTINUOU ┆ 17889.5   │
│        ┆            ┆ 09:00:17.5 ┆           ┆   ┆           ┆           ┆ S_TRADING ┆           │
│        ┆            ┆ 53216      ┆           ┆   ┆           ┆           ┆           ┆           │
│ GFI    ┆ 2023-01-03 ┆ 2023-01-03 ┆ 17801.0   ┆ … ┆ 308       ┆ 37476     ┆ CONTINUOU ┆ 17890.0   │
│        ┆            ┆ 09:00:17.5 ┆           ┆   ┆           ┆           ┆ S_TRADING ┆           │
│        ┆            ┆ 53323      ┆           ┆   ┆           ┆           ┆           ┆           │
│ GFI    ┆ 2023-01-03 ┆ 2023-01-03 ┆ 17801.0   ┆ … ┆ 308       ┆ 37480     ┆ CONTINUOU ┆ 17890.0   │
│        ┆            ┆ 09:00:17.5 ┆           ┆   ┆           ┆           ┆ S_TRADING ┆           │
│        ┆            ┆ 53417      ┆           ┆   ┆           ┆           ┆           ┆           │
│ GFI    ┆ 2023-01-03 ┆ 2023-01-03 ┆ 17801.0   ┆ … ┆ 490       ┆ 37485     ┆ CONTINUOU ┆ 17890.0   │
│        ┆            ┆ 09:00:17.5 ┆           ┆   ┆           ┆           ┆ S_TRADING ┆           │
│        ┆            ┆ 59032      ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [48]:
%%time
decay_df = []

z_max  = 2
z_grid = np.linspace(1, z_max, 200)

for day_D in metaorder_data.partition_by('Date'):

    date = day_D['Date'][0]
    #print(date)

    day_D = day_D.sort('Start time')
    num_metaorders = day_D.height

    for i in range(num_metaorders):

        row = day_D.row(i, named = True)

        if row['number child orders'] < 10:
            continue

        duration = row['durations (min)']

        delta_t    = (z_grid * duration).astype('timedelta64[m]')
        start_time = np.datetime64(row['Start time'])
        t_grid     = start_time + delta_t

        grid_df = pl.DataFrame({
            'query time': t_grid,
            'z'         : z_grid})
        
        grid_df = grid_df.sort('query time')

        candidate_df = stock_mid_prices.filter((pl.col('LocalTimestamp') >= grid_df['query time'][0]) & 
                                               (pl.col('LocalTimestamp') <= grid_df['query time'][-1]))

        merged = grid_df.join_asof(candidate_df, left_on = 'query time', right_on = 'LocalTimestamp', strategy = 'backward')

        merged = merged.drop_nulls(['BidPrice1', 'AskPrice1'])

        mid_prices = merged['Mid-price'].to_numpy()

        mid_prices_array     = np.full(len(mid_prices) + 2, np.nan)
        mid_prices_array[0]  = row['Mid-price before']
        mid_prices_array[1]  = row['Mid-price after']
        mid_prices_array[2:] = mid_prices

        z     = np.full(len(mid_prices) + 2, np.nan)
        z[0]  = 0
        z[1]  = 1
        z[2:] = merged['z'].to_numpy()

        Q      = row['volume traded']
        sigma  = row['20 AD volatility']
        volume = row['20 AD volume']
        sign   = row['trade sign']

        impact = sign * (np.log(mid_prices_array) - np.log(mid_prices_array[0]))

        scaled_impact_decay = impact / (np.sqrt(Q) * sigma)

        decay_df_day = pl.DataFrame({
            'Date'         : [date] * len(z),
            'z'            : z,
            'Q'            : [Q] * len(z),
            'sigma'        : [sigma] * len(z),
            'impact'       : impact,
            'scaled impact': scaled_impact_decay})

        decay_df.append(decay_df_day)

decay_df = pl.concat(decay_df, how = 'vertical', rechunk = True)

CPU times: user 19min 39s, sys: 1min 43s, total: 21min 23s
Wall time: 6min 11s

In [49]:
decay_df.head()

shape: (5, 6)
┌────────────┬──────────┬────────┬──────────┬───────────┬───────────────┐
│ Date       ┆ z        ┆ Q      ┆ sigma    ┆ impact    ┆ scaled impact │
│ ---        ┆ ---      ┆ ---    ┆ ---      ┆ ---       ┆ ---           │
│ date       ┆ f64      ┆ f64    ┆ f64      ┆ f64       ┆ f64           │
╞════════════╪══════════╪════════╪══════════╪═══════════╪═══════════════╡
│ 2023-01-03 ┆ 0.0      ┆ 1867.0 ┆ 0.042035 ┆ -0.0      ┆ -0.0          │
│ 2023-01-03 ┆ 1.0      ┆ 1867.0 ┆ 0.042035 ┆ NaN       ┆ NaN           │
│ 2023-01-03 ┆ 1.050251 ┆ 1867.0 ┆ 0.042035 ┆ -0.005714 ┆ -0.003146     │
│ 2023-01-03 ┆ 1.055276 ┆ 1867.0 ┆ 0.042035 ┆ -0.005714 ┆ -0.003146     │
│ 2023-01-03 ┆ 1.060302 ┆ 1867.0 ┆ 0.042035 ┆ -0.005714 ┆ -0.003146     │
└────────────┴──────────┴────────┴──────────┴───────────┴───────────────┘

In [51]:
decay_df.write_parquet(f'{ticker}_impact_decay_{identifier}.parquet')
b2.put_file(f'{ticker}_impact_decay_{identifier}.parquet', f'data/impact_decay/{identifier}')